name: Auto NSE Signals

on:
  schedule:
    - cron: "35 14 * * 1-5"   # 8:05 PM IST = 14:35 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: pip install pandas requests

      - name: Run NSE Signals
        run: python src/run_all.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Auto update" || echo "No changes"
          git push
          
